name: DSLA Contracts testing
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: NPM Install 
        with:
          node-version: 14
        run: npm i
      - name: Compile
        run: npx hardhat compile
      - name: Test
        run: npx hardhat test