/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IPeriodRegistryInterface extends ethers.utils.Interface {
  functions: {
    "getPeriodStartAndEnd(uint8,uint256)": FunctionFragment;
    "isInitializedPeriod(uint8)": FunctionFragment;
    "isValidPeriod(uint8,uint256)": FunctionFragment;
    "periodHasStarted(uint8,uint256)": FunctionFragment;
    "periodIsFinished(uint8,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getPeriodStartAndEnd",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isInitializedPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidPeriod",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "periodHasStarted",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "periodIsFinished",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPeriodStartAndEnd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInitializedPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "periodHasStarted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "periodIsFinished",
    data: BytesLike
  ): Result;

  events: {};
}

export class IPeriodRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IPeriodRegistryInterface;

  functions: {
    getPeriodStartAndEnd(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    isInitializedPeriod(
      _periodType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isValidPeriod(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    periodHasStarted(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    periodIsFinished(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  getPeriodStartAndEnd(
    _periodType: BigNumberish,
    _periodId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  isInitializedPeriod(
    _periodType: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isValidPeriod(
    _periodType: BigNumberish,
    _periodId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  periodHasStarted(
    _periodType: BigNumberish,
    _periodId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  periodIsFinished(
    _periodType: BigNumberish,
    _periodId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    getPeriodStartAndEnd(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    isInitializedPeriod(
      _periodType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isValidPeriod(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    periodHasStarted(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    periodIsFinished(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getPeriodStartAndEnd(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isInitializedPeriod(
      _periodType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidPeriod(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    periodHasStarted(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    periodIsFinished(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPeriodStartAndEnd(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isInitializedPeriod(
      _periodType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidPeriod(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    periodHasStarted(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    periodIsFinished(
      _periodType: BigNumberish,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
