/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ISLARegistryInterface extends ethers.utils.Interface {
  functions: {
    "isRegisteredSLA(address)": FunctionFragment;
    "messengerRegistry()": FunctionFragment;
    "periodRegistry()": FunctionFragment;
    "sloRegistry()": FunctionFragment;
    "stakeRegistry()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "isRegisteredSLA",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "messengerRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "periodRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sloRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakeRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "isRegisteredSLA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "messengerRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "periodRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sloRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeRegistry",
    data: BytesLike
  ): Result;

  events: {};
}

export class ISLARegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ISLARegistryInterface;

  functions: {
    isRegisteredSLA(
      _slaAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    messengerRegistry(overrides?: CallOverrides): Promise<[string]>;

    periodRegistry(overrides?: CallOverrides): Promise<[string]>;

    sloRegistry(overrides?: CallOverrides): Promise<[string]>;

    stakeRegistry(overrides?: CallOverrides): Promise<[string]>;
  };

  isRegisteredSLA(
    _slaAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  messengerRegistry(overrides?: CallOverrides): Promise<string>;

  periodRegistry(overrides?: CallOverrides): Promise<string>;

  sloRegistry(overrides?: CallOverrides): Promise<string>;

  stakeRegistry(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    isRegisteredSLA(
      _slaAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    messengerRegistry(overrides?: CallOverrides): Promise<string>;

    periodRegistry(overrides?: CallOverrides): Promise<string>;

    sloRegistry(overrides?: CallOverrides): Promise<string>;

    stakeRegistry(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    isRegisteredSLA(
      _slaAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    messengerRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    periodRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    sloRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    stakeRegistry(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    isRegisteredSLA(
      _slaAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    messengerRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    periodRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sloRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    stakeRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
