/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface StringUtilsInterface extends ethers.utils.Interface {
  functions: {
    "addressToString(address)": FunctionFragment;
    "bytes32ToStr(bytes32)": FunctionFragment;
    "bytesToUint(bytes)": FunctionFragment;
    "uintToStr(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addressToString",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "bytes32ToStr",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bytesToUint",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uintToStr",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addressToString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bytes32ToStr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bytesToUint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uintToStr", data: BytesLike): Result;

  events: {};
}

export class StringUtils extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: StringUtilsInterface;

  functions: {
    addressToString(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    bytes32ToStr(
      _bytes32: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    bytesToUint(
      b: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { result: BigNumber }>;

    uintToStr(
      _i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { _uintAsString: string }>;
  };

  addressToString(_address: string, overrides?: CallOverrides): Promise<string>;

  bytes32ToStr(_bytes32: BytesLike, overrides?: CallOverrides): Promise<string>;

  bytesToUint(b: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  uintToStr(_i: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addressToString(
      _address: string,
      overrides?: CallOverrides
    ): Promise<string>;

    bytes32ToStr(
      _bytes32: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    bytesToUint(b: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    uintToStr(_i: BigNumberish, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    addressToString(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bytes32ToStr(
      _bytes32: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bytesToUint(b: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    uintToStr(_i: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addressToString(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bytes32ToStr(
      _bytes32: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bytesToUint(
      b: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    uintToStr(
      _i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
