name: DSLA Contracts testing
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NPM Install 
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i
      - name: Compile
        run: npx hardhat compile
      - name: Test
        run: npx hardhat test