name: DSLA Contracts testing
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: NPM Install 
        with:
          node-version: 16
        run: npm i
      - name: Compile
        run: npx hardhat compile
      - name: Test
        run: npx hardhat test